Development to master
Dongmo12/Building-with-Backgrounds-and-Gradients pull request #4
Opened 2019-05-16 17:17 UTC by Dongmo12

Everything should be good now. Thanks for your help!!!

2019-05-17 20:37 UTC, AdnanAfsari commented
Hello @Dongmo12 :) 

Previous problem solved but arises a new one but do not worry its not a big one.

look at your down section- it is not taking the entire spaces but it should and also be equally distributed as the original one.
<img width="1280" alt="Screenshot 2019-05-18 at 2 31 20 AM" src="https://user-images.githubusercontent.com/8613710/57954570-1a0f5f80-7915-11e9-9e24-4dfaa4cec65d.png">



and looks at the original one 
<img width="1280" alt="Screenshot 2019-05-18 at 2 33 39 AM" src="https://user-images.githubusercontent.com/8613710/57954671-6490dc00-7915-11e9-82f1-06a6400c6d6b.png">

Please fix this issue and submit for another review :).Stay strong, i know the feeling but you have to do it.

Happy Coding

2019-07-09 01:48 UTC, Torres-ssf commented
### Great work team 👏
You did a nice job on this project. But I have to ask, this project was supposed to be done individually right? 
We need to make some changes in this project to make it in order with Microverse guidelines. The changes are:

- [ ] The main content should be wrapped around `main` tags and have an image set as background

- [ ] The navbar should be inside the main tag

- The 3 main sentences:
- [ ] There should be three links
- [ ] Each link is an `a` HTML tag, with a `div` tag inside it.
- [ ] The `div` tag inside the `a` tag should use an image as background. The text on the original page is actually an image

- [ ] Your last sentence is a lit bit under the next section. If possible try to match the original design. you can message me on slack for help if you need.

- Footer

- [ ] In this page the footer must starts at the div class="secondary-content". Its divides in 2 parts, top, and bottom.

- [ ] All 4 images must be inside an `a` tag each. And inside each `a` tag must be a div tag. You are going to load the images using only the background from the div tag. No need for img tags here.

- [ ] It seems that the bottom part of your footer it's on top the upper part.

- [ ]  There is one error in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

Kindly make these changes and submit for code review again.

2019-07-30 06:12 UTC, bolah2009 commented
PR currently been reviewed

2019-07-30 06:48 UTC, bolah2009 requested changes
## Nice Job [Armand](../../) :clap:

Awesome job so far, the [clone](https://raw.githack.com/Dongmo12/Building-with-Backgrounds-and-Gradients/development/index.html) looks nice. :clap: :+1: 

#### Just a few adjustment as explained in the comments below.

Good luck with your next submission.

Cheers
[Bola](https://bolabuari.com/)

2019-07-30 06:48 UTC, bolah2009 commented on Assets/stylesheet.css
> +} */
Consider deleting commented out code.

2019-07-30 06:48 UTC, bolah2009 commented on Assets/stylesheet.css
> +    width: 1268px;
`SUGGESTION`

Let's reposition the background image to fill the page as shown below:

|Current|Preffered|
| :-----: | :------: |
| ![appl com current](https://user-images.githubusercontent.com/36057474/62105869-899db580-b29b-11e9-9c97-ff6996ac5432.png)  |  ![preffered app](https://user-images.githubusercontent.com/36057474/62092488-488eac80-b26d-11e9-82c8-95cf194524fe.png) |

2019-07-30 06:48 UTC, bolah2009 commented on index.html
> +                        <li><a href="#"><i class="fab fa-apple"></i></a></li>
`REQUIRED`

The home icon (Apple image) seems not to be showing on the page. See below:


|Current|Preffered|
| :-----: | :------: |
| ![current apple home icon](https://user-images.githubusercontent.com/36057474/62106161-6cb5b200-b29c-11e9-9b1f-065c8648a3ea.png)  | ![preffered apple home icon png](https://user-images.githubusercontent.com/36057474/62106180-7a6b3780-b29c-11e9-835d-a3cba6812631.png)  |

2019-07-30 06:48 UTC, bolah2009 commented on Assets/stylesheet.css
> +    display: flex;
`REQUIRED`

Let's add `hover` effects to the `li` elements of the navbar. See image below:

|Current|Preffered|
| :-----: | :------: |
| ![current apple nav hover](https://user-images.githubusercontent.com/36057474/62106589-7e4b8980-b29d-11e9-8249-6afff62e582c.gif)  | ![preffered apple nav hover](https://user-images.githubusercontent.com/36057474/62106599-84da0100-b29d-11e9-929c-9fd802900bb5.gif)  |

2019-07-30 06:48 UTC, bolah2009 commented on index.html
> +                            <i class="fas fa-search"></i><input type="search" aria-label="search">
`SUGGESTION`

The `fas fa-search` is not rendering, it may be that you didn't link the `font awesome` assets properly, :thinking: ?

2019-07-30 12:02 UTC, bolah2009 commented
Currently under review

2019-07-30 12:10 UTC, bolah2009 approved these changes
## Awesome Job [Armand](../../) :clap:

### Some suggested changes are not yet implemented (check comment [1](https://github.com/Dongmo12/Building-with-Backgrounds-and-Gradients/pull/4#discussion_r308551772), [2](https://github.com/Dongmo12/Building-with-Backgrounds-and-Gradients/pull/4#discussion_r308553675), [3](https://github.com/Dongmo12/Building-with-Backgrounds-and-Gradients/pull/4#discussion_r308555748) and [4](https://github.com/Dongmo12/Building-with-Backgrounds-and-Gradients/pull/4#discussion_r308556670) ), I strongly recommend making those changes before merging.

Good luck with your next project.

Cheers
[Bola](https://bolabuari.com/)

2019-07-30 16:03 UTC, bolah2009 commented
# PR is approved :heavy_check_mark: :+1:

2019-07-30 20:14 UTC, merged